#!/usr/bin/python3
# SPDX-FileCopyright: 2022 Shusei Aida email:0912cocacola@gmail.com
# SPDX-License-Identifier: BSD-3-Clause

import sys


def tonum(s):
      try:
          return int(s)
      except:
          return float(s)


ans = 0 
for line in sys.stdin:
      line = line.rstrip()
      ans += tonum(line)

print('anser :',ans)