#!/usr/bin/python3
# SPDX-FileCopyright: 2022 Shusei Aida email:0912cocacola@gmail.com
# SPDX-License-Identifier: GPL-3.0

import sys


def tonum(s):
    try:
        ans += init(line)
    except:
        ans += float(line)

ans = 0
for line in sys.stdin:
   	 line = line.rstrip()
   	 ans += tonum(line)

print(ans)
ans += tonum(line)

print(ans)
